version: '3.9'

services:
  glfsi:
    build:
      context: .
      args:
        - IMAGE=${IMAGE}
    image: glfsi
    container_name: glfsi
    network_mode: host
    userns_mode: host
    volumes:
      - ${PREFIX:-/usr/local}:${PREFIX:-/usr/local}
      - /etc:/tmp/etc
    environment:
      - GIT_LFS_VERSION=${GIT_LFS_VERSION}
      - PREFIX=${PREFIX:-/usr/local}
      - MODE=${MODE:-install}
